### ISSUE TITLE
fresh setup nvim not working anymore. Giving ample errors

### ISSUE THREAD

**Issue by rob1121** [ChristianChiarulli/Neovim-from-scratch#139]
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/11769053/166976815-55a5cc2b-6e5c-4cb0-98d1-079c8585d1e7.png">

I tried to setup my nvim from this repo but no luck.

last time I got it with no errors. But when I tried to setup it on my new laptop it gives the errors

**Comment by heema** [comment]
it seam in the latest version of NvimTree plugin they migrated a lot of options
https://github.com/kyazdani42/nvim-tree.lua/issues/674

**Comment by xandro2021** [comment]
I have the same trouble. I was trying to get used to LunarVim because my own newie nvim config was too basic to change it for my vscode. I saw the long tutorial list of videos of this project in youtube and after watching the first one, I decided to give nvim a second try as an IDE because I like what it was showed.
I just deleted everything in ~/.cache/nvim  ~/.config/nvim and ~/.local/share/nvim (because I already have my basic newie setup backup in github)
The first time I run your installation command : "git clone https://github.com/LunarVim/Neovim-from-scratch.git ~/.config/nvim" everything were fine
then I run nvim and then all the packages were installed successfully  except treesitter. then I removed everything again, include the nvim that came with fedora 35 (neovim 0.6.1). Downloaded the lastest stable release (0.7.0), restarted the process but this time I modified treesitter.lua to change ensure_installed = "maintened" => ensure_intalled = "all".
start nvim(0.7.0) and finally again everything was installed but treesitter again giving troubles. then I closed it and opened it again, and finally I was able to se the neovim welcome page of this project, but with the problem described by rob1121.

![muestra](https://user-images.githubusercontent.com/88587370/167196581-c4f0cf81-18ed-4802-b76c-1e0b92175e77.png)


But I'm just a newer Vim user who doesn't know anything about lua nor vim.g nor let g:
I tried the commented lines but yeap, those are syntaxis used for a vim.g but I don't know how to do it and append it to the file.
Guess I'm just to try spacevim adding my favorites plugins and colorschemes, or just stick with a real IDE like VsCode and just add a Vim extension to it. The amount of time required to turn vim or neovim into a IDE is just insane, and instead of learning vimscript, or lua I would prefer to focus on learning web developing :/ , and everything just get worst if the setup gets broken by changes made by one of plugins like those var name changes in nvim-tree.lua

**Comment by gnmearacaun** [comment]
Yeah, the treesitter issue usually resolves itself soon after a fresh install and running :PackerSync. It's a shame that some errors have crept in lately with plugin changes, as this config was solid up to a couple of weeks ago. No doubt it will be again soon... In the meantime you could use this config that works ootb (for LunarVim only) https://github.com/kylo252/lvim

**Comment by brianrobt** [comment]
@gnmearacaun I am running into the same issue as @xandro2021.  Running :PackerSync after intalling treesitter didn't fix the issue for me.  I also tried running `:TSUninstall lua`, then `:TSInstall lua`, which both didn't resolve the issue either.  I'm working on finding a fix for this as we speak.

**Comment by gnmearacaun** [comment]
I've got mine working again. I reverted to a working version I had saved and fixed the minor errors by commenting out and so forth. Here is a fix for the nvim-tree errors that @rob1121 mentions above https://github.com/LunarVim/Neovim-from-scratch/pull/145#issue-1230158771 There's nothing worse than having a broken config to fix your broken config :t-rex:

**Comment by brianrobt** [comment]
I got the tree errors resolved as well.  Thanks for that.  I have a couple of errors like the one below, which is the main issue right now.  It looks like a couple of plugins aren't able to find the new `vim.api.nvim_create_user_command` function.  I am using nvim 0.7.0 which is being built from source.  I'm not sure what's going on there.  This error occurs for `telescope`, `bufferline`, and `cmp`.

```bash
E5113: Error while calling lua chunk: ...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:108: attempt to call field 'nvim_create_user_command' (a nil value)
```

**Comment by brianrobt** [comment]
The latest `nvim` (0.8.0) build from master fixed these issues for me.

**Comment by gnmearacaun** [comment]
> The latest `nvim` (0.8.0) build from master fixed these issues for me.

Glad to hear it. I'm on v0.8.0 too.
