### ISSUE TITLE
Icons not appearing properly

### ISSUE THREAD

**Issue by ghost** [ChristianChiarulli/Neovim-from-scratch#5]
Successful install, but icons are not showing properly across the board.

![image](https://user-images.githubusercontent.com/19592432/146590322-3e6cd009-8cf6-4cc2-9469-c0441f2ccb63.png)

**Comment by utilyre** [comment]
Do you have a nerd font installed?
see [nerd-fonts repository](https://github.com/ryanoasis/nerd-fonts)

**EDIT**: btw, he has a video about installing a nerd font [here](https://youtu.be/fR4ThXzhQYI)

**Comment by ghost** [comment]
I do, I have the Mononoki nerd font installed.

EDIT: Not sure why it was broken with Mononoki. I switched to the Hack font mentioned in the video shared above. All seems good now! I appreciate your help!

**Comment by paras-verma** [comment]
this is issue still persists (with HackNF installed) in some places

it'd be great if there was a list of all (if more than one) nerd font(s) used

![image](https://user-images.githubusercontent.com/56761068/146997587-e4be85de-7322-4981-af9b-3d951538b49f.png)

![image](https://user-images.githubusercontent.com/56761068/146997485-0b7a5ae2-b873-4da2-bf0a-3b58488ea0eb.png)

**Comment by meicale** [comment]
Problem solved? Can you use these fonts when using terminal like mobaxterm??

**Comment by utilyre** [comment]
First of all I apologize I'm responding late.

This issue is most likely from your terminal emulator not the neovim-from-scratch project. So if you are sure that you've configured the terminal emulator properly (including setting the font or the backup font to a nerdfont), open an issue on that specific terminal's repository to get it fixed :)
