### ISSUE TITLE
lsp format error

### ISSUE THREAD

**Issue by fleongg** [ChristianChiarulli/Neovim-from-scratch#80]
After the installation, I install pyright by :LspInstallInfo. Then I open a python file and press space + l + f, then the following error appears:

`[null-ls] [ERROR 02:34:37] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:180: command black is not executable (make sure it's installed and on your $PATH)`

I see there is a replica of this error, but the issue is closed without answer. I have done some research and still cannot solve it.

**Comment by hpb0412** [comment]
From the error message, I guess your `neovim` is using `null-ls`'s `black` formatter instead of `nvim-lsp`'s `pyright` as your expectation.

`pyright` is not a formatter, it is `Static type checker for python` (https://github.com/microsoft/pyright)

So install `pyright` doesn't add formatting feature to your neovim.

Instead it fallbacks to `null-ls`'s `black`.

So you must install `black` to your system to get rid of this error.
If you have installed it, it could be the tool is not in the `PATH`. make sure you add the path to the tool to `PATH` env var.

**Comment by fleongg** [comment]
It works when I install black by homebrew! Thank you so much!
